version: "3.8"
# specify the services to be run (containers)
services:
  servers:
    image: 'nginx:stable-alpine'
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  php:
  mysql:
  composer:
  artisan:
  npm:
  